### ISSUE TITLE
When choosing "Not in the U.S.?" option, Firefox asks to fill-in a field that is not currently displayed

### ISSUE THREAD

**Issue by Rillke** [EFForg/ngw-website#6]
Version: Live version.
Browser: Mozilla Firefox 47, some privacy Add-Ons running
iFrame URL: [act.eff.org](https://act.eff.org/action/noglobalwarrants-petition/embed_iframe?&css=https%3A%2F%2Fwww.eff.org%2Ffiles%2Fwidget%2Fngw-embed.css&international_only=true&non_us_option=petition)
Reproducible: Always.
How to reproduce: Go  to https://noglobalwarrants.org/#background and hit the "Not in the U.S.?" link, fill in all fields and press "speak out".

Result:
![13466068_1151834688201077_60925934251920050_n](https://cloud.githubusercontent.com/assets/2311611/16233471/c2ac735c-37ce-11e6-83fa-b86260f3273c.jpg)

And signature is not submitted.

**Comment by mfb** [comment]
Strange, I haven't reproduced this.

**Comment by maximillianh** [comment]
It's reproducible every time for users if you don't have a logged-in session for the action center.  You must be have ngw-website checked out to bc64f399901243c0bef796841693fc6de15d3046

**Comment by mfb** [comment]
I don't have a logged-in session and not reproducing it on the live site.

**Comment by Rillke** [comment]
> I don't have a logged-in session and not reproducing it on the live site.

Can I somehow help you to reproduce? E.g. Video recording, copy of the DOM?

**Comment by mfb** [comment]
I think there have been some updates to the live site so this isn't reproducible there - if you clear your browser cache.  There is however a new issue, having to click both "Not in the US" and "Outside the US"

**Comment by Rillke** [comment]
Yeah, I see, thanks.

**Comment by mfb** [comment]
re-opening to fix the underlying issue
